version: '3'
services:
  employees-service:
    image: fran902/time-off-employees
    mem_limit: 128m
    hostname: employees-service
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  leave-requests-service:
    image: fran902/time-off-requests
    mem_limit: 128m
    hostname: leave-requests-service
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  email-generation-srv:
    image: fran902/time-off-email-gen
    mem_limit: 128m
    hostname: email-generation-srv
  auth-srv:
    image: fran902/time-off-auth
    mem_limit: 128m
    hostname: authentication-service
  image: fran902/time-off-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  
